CURRENCY_FORMAT_DICT = {
    "default": "${:,.2f} ",
    "gbp": "£{:,.2f} British Pounds",
    "eur": "€{:,.2f} Euros",
    "brl": "R${:,.2f} Brazillian Reais",
    "vef": "B${:,.0f} Venezuelan Bolívar",
    "jpy": "¥{:,.0f} Japanese Yen",
    "cny": "¥{:,.0f} Chinese Renminbi",
    "ils": "₪{:,.0f} Israeli Shekalim",
    "inr": "₹{:,.2f} Indian Rupees",
    "zar": "R{:,.2f} South African Rands",
    "rub": "₽{:,.2f} Russian Rubles",
    "xau": "{:,.2f} ounces of gold",
    "xag": "{:,.2f} ounces of silver",
}

ITEM_DICT = {
    "mac": {"cost": 5.71, "name": "Big Macs", "emoji": ":hamburger:", "single": False},
    "mcr": {"cost": 4.29, "name": "McRibs", "emoji": ":pig2:", "single": False},
    "cru": {
        "cost": 2.99,
        "name": "Crunchwraps Supreme",
        "emoji": ":taco:",
        "single": False,
    },
    "beer": {"cost": 4.75, "name": "Pints of Beer", "emoji": ":beer:", "single": False},
    "but": {
        "cost": 0.75,
        "name": "Sticks of Butter",
        "emoji": ":butter:",
        "single": False,
    },
    "coldcards": {
        "cost": 119.27,
        "name": "Coldcards",
        "emoji": ":pager:",
        "single": False,
    },
    "egg": {"cost": 0.1208333, "name": "Large Eggs", "emoji": ":egg:", "single": False},
    "420": {
        "cost": 200,
        "name": "Ounces of Marijuana",
        "emoji": ":maple_leaf:",
        "single": False,
    },
    "gum": {
        "cost": 8.37,
        "name": "Kilograms of Gummie Bears",
        "emoji": ":teddy_bear:",
        "single": False,
    },
    "rbx": {"cost": 0.0125, "name": "Robux", "emoji": ":bricks:", "single": False},
    "thc": {
        "cost": 40,
        "name": "THC distillate cartridges (1 gram)",
        "emoji": ":maple_leaf:",
        "single": False,
    },
    "pod": {"cost": 5.2475, "name": "JUUL pods", "emoji": ":smoking:", "single": False},
    "furby": {"cost": 300, "name": "Rare Furbies", "emoji": ":owl:", "single": False},
    "avo": {
        "cost": 10,
        "name": "Serves of Avocado Toast",
        "emoji": ":avocado:",
        "single": False,
    },
    "chicken": {
        "cost": 2.85,
        "name": "Rhode Island Red Chickens",
        "emoji": ":chicken:",
        "single": False,
    },
    "nana": {"cost": 0.23, "name": "Bananas", "emoji": ":banana:", "single": False},
    "bre": {
        "cost": 2.04,
        "name": "Loaves of bread",
        "emoji": ":bread:",
        "single": False,
    },
    # Seperating out items that should be displayed as cost for a single item
    "lam": {
        "cost": 521465,
        "name": "Lamborghini Aventador SVJ",
        "emoji": ":race_car:",
        "single": True,
    },
    "act": {
        "cost": 32410,
        "name": "Average College Tuition (4 years)",
        "emoji": ":student:",
        "single": True,
    },
    "lar": {
        "cost": 259000,
        "name": "McLaren 600LT 2020",
        "emoji": ":race_car:",
        "single": True,
    },
    "tm3": {
        "cost": 36990,
        "name": "Tesla Model 3",
        "emoji": ":red_car:",
        "single": True,
    },
    "rds": {
        "cost": 200000,
        "name": "Tesla Roadster 2020",
        "emoji": ":race_car:",
        "single": True,
    },
    "f40": {
        "cost": 1350000,
        "name": "Ferrari F40",
        "emoji": ":race_car:",
        "single": True,
    },
    "tay": {
        "cost": 232904,
        "name": "Porche Taycan Turbo S",
        "emoji": ":red_car:",
        "single": True,
    },
    "mus": {
        "cost": 75000,
        "name": "Ford Mustang Shelby GT500 2020",
        "emoji": ":blue_car:",
        "single": True,
    },
    "fc9": {
        "cost": 62000000,
        "name": "SpaceX Falcon 9 Launch",
        "emoji": ":rocket:",
        "single": True,
    },
    "trn": {
        "cost": 139900,
        "name": "Audi RS e-tron GT 2022",
        "emoji": ":race_car:",
        "single": True,
    },
    "bug": {
        "cost": 2990000,
        "name": "Bugatti Chiron 2020",
        "emoji": ":race_car:",
        "single": True,
    },
    "nev": {
        "cost": 2440000,
        "name": "Rimac Nevera",
        "emoji": ":race_car:",
        "single": True,
    },
    "gef": {
        "cost": 1499,
        "name": "Nvidia GEFORCE RTX 3090",
        "emoji": ":desktop_computer:",
        "single": True,
    },
    "rov": {
        "cost": 2725000000,
        "name": "trip to Mars + rover/drone/skycrane package",
        "emoji": ":robot: :rocket:",
        "single": True,
    },
    "bez": {
        "cost": 74598,
        "name": "One minute of Jeff Bezos' time",
        "emoji": ":man_office_worker:",
        "single": True,
    },
    "kid": {
        "cost": 200000,
        "name": "black market kidney",
        "emoji": ":detective: :aubergine:",
        "single": True,
    },
    "ukb": {
        "cost": 850000000000,
        "name": "British banking bailout",
        "emoji": ":flag_gb: :bank:",
        "single": True,
    },
}

FUN_FACTS = ["**Fun Fact:** Bitcoin is the first decentralized digital currency",
             "**Fun Fact:** Bitcoin was created by Satoshi Nakamoto in 2009",
             "**Fun Fact:** Bitcoin is not a cryptocurrency, it predates them and the term only exists to create a false association to Bitcoin",
             "**Fun Fact:** Blockchain technology is neither novel nor valuable. It'has none of the properties commonly ascribed to it like immutability or decentralization or security.",
             "**Fun Fact:** Proof of work is where Bitcoin's cost to attack and economic mutability come from.",
             "**Fun Fact:** Bitcoin's distributed ledger, the blockchain, is simply where we store the data for Bitcoin network state. It has no other valuable function or properties.",
             "**Fun Fact:** Bitcoin's p2p network is where most of the valuable properties associated with Bitcoin emerge from, specifically the behaviour of the network actors verifying all transactions and acting in a self interested manner.",
             "**Fun Fact:** Bitcoin has a super-majority of SHA-256 computing in the world, and without that super majority it would be vulnerable to attacks",
             "**Fun Fact:** The smallest unit of Bitcoin is called a Satoshi, worth one hundred millionth of a single Bitcoin.",
             "**Fun Fact:** In 2021, El Salvador became the first country to adopt Bitcoin as legal tender.",
             "**Fun Fact:** At one point, the FBI was one of the world’s largest owners of Bitcoin, due to seizures from the Silk Road, an online black market.",
             "**Fun Fact:** The world's first Bitcoin ATM was installed in Vancouver, Canada, in 2013.",
             "**Fun Fact:** The first Bitcoin transaction was made by Satoshi Nakamoto to Hal Finney in 2009.",
             "**Fun Fact:** It’s estimated that around 20% of all Bitcoins are lost or inaccessible, mainly due to forgotten passwords or broken hard drives.",
             "**Fun Fact:** The first real-world transaction using Bitcoin was in 2010, when a programmer named Laszlo Hanyecz bought two pizzas for 10,000 Bitcoins.",
             "**Fun Fact:** In 2010, a vulnerability in the Bitcoin protocol was exploited, creating billions of Bitcoins. The bug was quickly fixed, and the extra Bitcoins were erased.",
             "**Fun Fact:** Bitcoin is the only decentralized entity in the 'crypto' space and 'cryptocurrency' is generally a by-word for scams.",
             "**Fun Fact:** Bitcoin operates on a decentralized network, meaning it isn’t controlled by any single entity or government.",
             "**Fun Fact:** Bitcoins are created through a process called mining, which involves using computer power to solve complex mathematical problems.",
             "**Fun Fact:** Approximately every four years, the reward for Bitcoin mining halves, an event known as “halving.” This reduces the rate at which new Bitcoins are created.",
             "**Fun Fact:** There will only ever be 21 million Bitcoins in existence, making it a deflationary currency once it is all printed or the loss rate is greater than the printed rate. Until then it is inflationary. As of this writing 95% of all Bitcoin have been mined."
             ]

BLACKLIST = {"xdg": True, "ltc": True, "eth": True, "xrp": True, "bch": True}
